language: python
python:
  - "3.6"
branches:
  only:
    - source
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - git submodule update --init --recursive
script:
  - make publish
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: output
  github_token: $GH_TOKEN
